# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiViewContext(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'str',
        'view_fields': 'list[ConquestApiViewField]'
    }

    attribute_map = {
        'context': 'Context',
        'view_fields': 'ViewFields'
    }

    def __init__(self, context=None, view_fields=None):  # noqa: E501
        """ConquestApiViewContext - a model defined in Swagger"""  # noqa: E501
        self._context = None
        self._view_fields = None
        self.discriminator = None
        if context is not None:
            self.context = context
        if view_fields is not None:
            self.view_fields = view_fields

    @property
    def context(self):
        """Gets the context of this ConquestApiViewContext.  # noqa: E501


        :return: The context of this ConquestApiViewContext.  # noqa: E501
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this ConquestApiViewContext.


        :param context: The context of this ConquestApiViewContext.  # noqa: E501
        :type: str
        """

        self._context = context

    @property
    def view_fields(self):
        """Gets the view_fields of this ConquestApiViewContext.  # noqa: E501


        :return: The view_fields of this ConquestApiViewContext.  # noqa: E501
        :rtype: list[ConquestApiViewField]
        """
        return self._view_fields

    @view_fields.setter
    def view_fields(self, view_fields):
        """Sets the view_fields of this ConquestApiViewContext.


        :param view_fields: The view_fields of this ConquestApiViewContext.  # noqa: E501
        :type: list[ConquestApiViewField]
        """

        self._view_fields = view_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiViewContext, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiViewContext):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
