# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiAddGeoUpdateCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'overwrite': 'bool',
        'x_dont_start': 'bool'
    }

    attribute_map = {
        'overwrite': 'Overwrite',
        'x_dont_start': 'XDontStart'
    }

    def __init__(self, overwrite=None, x_dont_start=None):  # noqa: E501
        """ConquestApiAddGeoUpdateCommand - a model defined in Swagger"""  # noqa: E501
        self._overwrite = None
        self._x_dont_start = None
        self.discriminator = None
        if overwrite is not None:
            self.overwrite = overwrite
        if x_dont_start is not None:
            self.x_dont_start = x_dont_start

    @property
    def overwrite(self):
        """Gets the overwrite of this ConquestApiAddGeoUpdateCommand.  # noqa: E501


        :return: The overwrite of this ConquestApiAddGeoUpdateCommand.  # noqa: E501
        :rtype: bool
        """
        return self._overwrite

    @overwrite.setter
    def overwrite(self, overwrite):
        """Sets the overwrite of this ConquestApiAddGeoUpdateCommand.


        :param overwrite: The overwrite of this ConquestApiAddGeoUpdateCommand.  # noqa: E501
        :type: bool
        """

        self._overwrite = overwrite

    @property
    def x_dont_start(self):
        """Gets the x_dont_start of this ConquestApiAddGeoUpdateCommand.  # noqa: E501


        :return: The x_dont_start of this ConquestApiAddGeoUpdateCommand.  # noqa: E501
        :rtype: bool
        """
        return self._x_dont_start

    @x_dont_start.setter
    def x_dont_start(self, x_dont_start):
        """Sets the x_dont_start of this ConquestApiAddGeoUpdateCommand.


        :param x_dont_start: The x_dont_start of this ConquestApiAddGeoUpdateCommand.  # noqa: E501
        :type: bool
        """

        self._x_dont_start = x_dont_start

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiAddGeoUpdateCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiAddGeoUpdateCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
