# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiFieldDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_caption': 'str',
        'field_name': 'str',
        'table_caption': 'str',
        'table_name': 'str'
    }

    attribute_map = {
        'field_caption': 'FieldCaption',
        'field_name': 'FieldName',
        'table_caption': 'TableCaption',
        'table_name': 'TableName'
    }

    def __init__(self, field_caption=None, field_name=None, table_caption=None, table_name=None):  # noqa: E501
        """ConquestApiFieldDescription - a model defined in Swagger"""  # noqa: E501
        self._field_caption = None
        self._field_name = None
        self._table_caption = None
        self._table_name = None
        self.discriminator = None
        if field_caption is not None:
            self.field_caption = field_caption
        if field_name is not None:
            self.field_name = field_name
        if table_caption is not None:
            self.table_caption = table_caption
        if table_name is not None:
            self.table_name = table_name

    @property
    def field_caption(self):
        """Gets the field_caption of this ConquestApiFieldDescription.  # noqa: E501


        :return: The field_caption of this ConquestApiFieldDescription.  # noqa: E501
        :rtype: str
        """
        return self._field_caption

    @field_caption.setter
    def field_caption(self, field_caption):
        """Sets the field_caption of this ConquestApiFieldDescription.


        :param field_caption: The field_caption of this ConquestApiFieldDescription.  # noqa: E501
        :type: str
        """

        self._field_caption = field_caption

    @property
    def field_name(self):
        """Gets the field_name of this ConquestApiFieldDescription.  # noqa: E501


        :return: The field_name of this ConquestApiFieldDescription.  # noqa: E501
        :rtype: str
        """
        return self._field_name

    @field_name.setter
    def field_name(self, field_name):
        """Sets the field_name of this ConquestApiFieldDescription.


        :param field_name: The field_name of this ConquestApiFieldDescription.  # noqa: E501
        :type: str
        """

        self._field_name = field_name

    @property
    def table_caption(self):
        """Gets the table_caption of this ConquestApiFieldDescription.  # noqa: E501


        :return: The table_caption of this ConquestApiFieldDescription.  # noqa: E501
        :rtype: str
        """
        return self._table_caption

    @table_caption.setter
    def table_caption(self, table_caption):
        """Sets the table_caption of this ConquestApiFieldDescription.


        :param table_caption: The table_caption of this ConquestApiFieldDescription.  # noqa: E501
        :type: str
        """

        self._table_caption = table_caption

    @property
    def table_name(self):
        """Gets the table_name of this ConquestApiFieldDescription.  # noqa: E501


        :return: The table_name of this ConquestApiFieldDescription.  # noqa: E501
        :rtype: str
        """
        return self._table_name

    @table_name.setter
    def table_name(self, table_name):
        """Sets the table_name of this ConquestApiFieldDescription.


        :param table_name: The table_name of this ConquestApiFieldDescription.  # noqa: E501
        :type: str
        """

        self._table_name = table_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiFieldDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiFieldDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
