# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiGetUploadTokenReponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'upload_token': 'ConquestApiUploadToken'
    }

    attribute_map = {
        'upload_token': 'UploadToken'
    }

    def __init__(self, upload_token=None):  # noqa: E501
        """ConquestApiGetUploadTokenReponse - a model defined in Swagger"""  # noqa: E501
        self._upload_token = None
        self.discriminator = None
        if upload_token is not None:
            self.upload_token = upload_token

    @property
    def upload_token(self):
        """Gets the upload_token of this ConquestApiGetUploadTokenReponse.  # noqa: E501


        :return: The upload_token of this ConquestApiGetUploadTokenReponse.  # noqa: E501
        :rtype: ConquestApiUploadToken
        """
        return self._upload_token

    @upload_token.setter
    def upload_token(self, upload_token):
        """Sets the upload_token of this ConquestApiGetUploadTokenReponse.


        :param upload_token: The upload_token of this ConquestApiGetUploadTokenReponse.  # noqa: E501
        :type: ConquestApiUploadToken
        """

        self._upload_token = upload_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiGetUploadTokenReponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiGetUploadTokenReponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
