# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'report_definition': 'str',
        'report_name': 'str'
    }

    attribute_map = {
        'report_definition': 'ReportDefinition',
        'report_name': 'ReportName'
    }

    def __init__(self, report_definition=None, report_name=None):  # noqa: E501
        """ConquestApiReport - a model defined in Swagger"""  # noqa: E501
        self._report_definition = None
        self._report_name = None
        self.discriminator = None
        if report_definition is not None:
            self.report_definition = report_definition
        if report_name is not None:
            self.report_name = report_name

    @property
    def report_definition(self):
        """Gets the report_definition of this ConquestApiReport.  # noqa: E501


        :return: The report_definition of this ConquestApiReport.  # noqa: E501
        :rtype: str
        """
        return self._report_definition

    @report_definition.setter
    def report_definition(self, report_definition):
        """Sets the report_definition of this ConquestApiReport.


        :param report_definition: The report_definition of this ConquestApiReport.  # noqa: E501
        :type: str
        """

        self._report_definition = report_definition

    @property
    def report_name(self):
        """Gets the report_name of this ConquestApiReport.  # noqa: E501


        :return: The report_name of this ConquestApiReport.  # noqa: E501
        :rtype: str
        """
        return self._report_name

    @report_name.setter
    def report_name(self, report_name):
        """Sets the report_name of this ConquestApiReport.


        :param report_name: The report_name of this ConquestApiReport.  # noqa: E501
        :type: str
        """

        self._report_name = report_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
