# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiTrimDocumentsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'trim_documents': 'list[ConquestApiTrimDocument]'
    }

    attribute_map = {
        'trim_documents': 'TrimDocuments'
    }

    def __init__(self, trim_documents=None):  # noqa: E501
        """ConquestApiTrimDocumentsResponse - a model defined in Swagger"""  # noqa: E501
        self._trim_documents = None
        self.discriminator = None
        if trim_documents is not None:
            self.trim_documents = trim_documents

    @property
    def trim_documents(self):
        """Gets the trim_documents of this ConquestApiTrimDocumentsResponse.  # noqa: E501


        :return: The trim_documents of this ConquestApiTrimDocumentsResponse.  # noqa: E501
        :rtype: list[ConquestApiTrimDocument]
        """
        return self._trim_documents

    @trim_documents.setter
    def trim_documents(self, trim_documents):
        """Sets the trim_documents of this ConquestApiTrimDocumentsResponse.


        :param trim_documents: The trim_documents of this ConquestApiTrimDocumentsResponse.  # noqa: E501
        :type: list[ConquestApiTrimDocument]
        """

        self._trim_documents = trim_documents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiTrimDocumentsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiTrimDocumentsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
