# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiTrimStatusResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_user': 'str',
        'database_id': 'str',
        'database_name': 'str'
    }

    attribute_map = {
        'current_user': 'CurrentUser',
        'database_id': 'DatabaseId',
        'database_name': 'DatabaseName'
    }

    def __init__(self, current_user=None, database_id=None, database_name=None):  # noqa: E501
        """ConquestApiTrimStatusResponse - a model defined in Swagger"""  # noqa: E501
        self._current_user = None
        self._database_id = None
        self._database_name = None
        self.discriminator = None
        if current_user is not None:
            self.current_user = current_user
        if database_id is not None:
            self.database_id = database_id
        if database_name is not None:
            self.database_name = database_name

    @property
    def current_user(self):
        """Gets the current_user of this ConquestApiTrimStatusResponse.  # noqa: E501


        :return: The current_user of this ConquestApiTrimStatusResponse.  # noqa: E501
        :rtype: str
        """
        return self._current_user

    @current_user.setter
    def current_user(self, current_user):
        """Sets the current_user of this ConquestApiTrimStatusResponse.


        :param current_user: The current_user of this ConquestApiTrimStatusResponse.  # noqa: E501
        :type: str
        """

        self._current_user = current_user

    @property
    def database_id(self):
        """Gets the database_id of this ConquestApiTrimStatusResponse.  # noqa: E501


        :return: The database_id of this ConquestApiTrimStatusResponse.  # noqa: E501
        :rtype: str
        """
        return self._database_id

    @database_id.setter
    def database_id(self, database_id):
        """Sets the database_id of this ConquestApiTrimStatusResponse.


        :param database_id: The database_id of this ConquestApiTrimStatusResponse.  # noqa: E501
        :type: str
        """

        self._database_id = database_id

    @property
    def database_name(self):
        """Gets the database_name of this ConquestApiTrimStatusResponse.  # noqa: E501


        :return: The database_name of this ConquestApiTrimStatusResponse.  # noqa: E501
        :rtype: str
        """
        return self._database_name

    @database_name.setter
    def database_name(self, database_name):
        """Sets the database_name of this ConquestApiTrimStatusResponse.


        :param database_name: The database_name of this ConquestApiTrimStatusResponse.  # noqa: E501
        :type: str
        """

        self._database_name = database_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiTrimStatusResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiTrimStatusResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
