# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiCreateSessionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'ConquestApiErrorResponse',
        'token_response': 'ConquestApiAuthTokenResponse'
    }

    attribute_map = {
        'error': 'Error',
        'token_response': 'TokenResponse'
    }

    def __init__(self, error=None, token_response=None):  # noqa: E501
        """ConquestApiCreateSessionResponse - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._token_response = None
        self.discriminator = None
        if error is not None:
            self.error = error
        if token_response is not None:
            self.token_response = token_response

    @property
    def error(self):
        """Gets the error of this ConquestApiCreateSessionResponse.  # noqa: E501


        :return: The error of this ConquestApiCreateSessionResponse.  # noqa: E501
        :rtype: ConquestApiErrorResponse
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ConquestApiCreateSessionResponse.


        :param error: The error of this ConquestApiCreateSessionResponse.  # noqa: E501
        :type: ConquestApiErrorResponse
        """

        self._error = error

    @property
    def token_response(self):
        """Gets the token_response of this ConquestApiCreateSessionResponse.  # noqa: E501


        :return: The token_response of this ConquestApiCreateSessionResponse.  # noqa: E501
        :rtype: ConquestApiAuthTokenResponse
        """
        return self._token_response

    @token_response.setter
    def token_response(self, token_response):
        """Sets the token_response of this ConquestApiCreateSessionResponse.


        :param token_response: The token_response of this ConquestApiCreateSessionResponse.  # noqa: E501
        :type: ConquestApiAuthTokenResponse
        """

        self._token_response = token_response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiCreateSessionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiCreateSessionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
