# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiAttributeSetFieldNames(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_names': 'list[str]',
        'object_type': 'ConquestApiObjectType'
    }

    attribute_map = {
        'field_names': 'FieldNames',
        'object_type': 'ObjectType'
    }

    def __init__(self, field_names=None, object_type=None):  # noqa: E501
        """ConquestApiAttributeSetFieldNames - a model defined in Swagger"""  # noqa: E501
        self._field_names = None
        self._object_type = None
        self.discriminator = None
        if field_names is not None:
            self.field_names = field_names
        if object_type is not None:
            self.object_type = object_type

    @property
    def field_names(self):
        """Gets the field_names of this ConquestApiAttributeSetFieldNames.  # noqa: E501


        :return: The field_names of this ConquestApiAttributeSetFieldNames.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_names

    @field_names.setter
    def field_names(self, field_names):
        """Sets the field_names of this ConquestApiAttributeSetFieldNames.


        :param field_names: The field_names of this ConquestApiAttributeSetFieldNames.  # noqa: E501
        :type: list[str]
        """

        self._field_names = field_names

    @property
    def object_type(self):
        """Gets the object_type of this ConquestApiAttributeSetFieldNames.  # noqa: E501


        :return: The object_type of this ConquestApiAttributeSetFieldNames.  # noqa: E501
        :rtype: ConquestApiObjectType
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """Sets the object_type of this ConquestApiAttributeSetFieldNames.


        :param object_type: The object_type of this ConquestApiAttributeSetFieldNames.  # noqa: E501
        :type: ConquestApiObjectType
        """

        self._object_type = object_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiAttributeSetFieldNames, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiAttributeSetFieldNames):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
