# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiDocumentTypeMigrationProgress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'doc_type': 'str',
        'item_processed': 'int',
        'total_items': 'int'
    }

    attribute_map = {
        'doc_type': 'DocType',
        'item_processed': 'ItemProcessed',
        'total_items': 'TotalItems'
    }

    def __init__(self, doc_type=None, item_processed=None, total_items=None):  # noqa: E501
        """ConquestApiDocumentTypeMigrationProgress - a model defined in Swagger"""  # noqa: E501
        self._doc_type = None
        self._item_processed = None
        self._total_items = None
        self.discriminator = None
        if doc_type is not None:
            self.doc_type = doc_type
        if item_processed is not None:
            self.item_processed = item_processed
        if total_items is not None:
            self.total_items = total_items

    @property
    def doc_type(self):
        """Gets the doc_type of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501


        :return: The doc_type of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501
        :rtype: str
        """
        return self._doc_type

    @doc_type.setter
    def doc_type(self, doc_type):
        """Sets the doc_type of this ConquestApiDocumentTypeMigrationProgress.


        :param doc_type: The doc_type of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501
        :type: str
        """

        self._doc_type = doc_type

    @property
    def item_processed(self):
        """Gets the item_processed of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501


        :return: The item_processed of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501
        :rtype: int
        """
        return self._item_processed

    @item_processed.setter
    def item_processed(self, item_processed):
        """Sets the item_processed of this ConquestApiDocumentTypeMigrationProgress.


        :param item_processed: The item_processed of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501
        :type: int
        """

        self._item_processed = item_processed

    @property
    def total_items(self):
        """Gets the total_items of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501


        :return: The total_items of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items):
        """Sets the total_items of this ConquestApiDocumentTypeMigrationProgress.


        :param total_items: The total_items of this ConquestApiDocumentTypeMigrationProgress.  # noqa: E501
        :type: int
        """

        self._total_items = total_items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiDocumentTypeMigrationProgress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiDocumentTypeMigrationProgress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
