# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiChangeDocumentContentCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'content_length': 'str',
        'content_type': 'str',
        'document_description': 'str',
        'document_id': 'int',
        'hashes': 'list[str]',
        'link_existing_document': 'bool',
        'object_key': 'ConquestApiObjectKey',
        'update_time': 'datetime'
    }

    attribute_map = {
        'address': 'Address',
        'content_length': 'ContentLength',
        'content_type': 'ContentType',
        'document_description': 'DocumentDescription',
        'document_id': 'DocumentID',
        'hashes': 'Hashes',
        'link_existing_document': 'LinkExistingDocument',
        'object_key': 'ObjectKey',
        'update_time': 'UpdateTime'
    }

    def __init__(self, address=None, content_length=None, content_type=None, document_description=None, document_id=None, hashes=None, link_existing_document=None, object_key=None, update_time=None):  # noqa: E501
        """ConquestApiChangeDocumentContentCommand - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._content_length = None
        self._content_type = None
        self._document_description = None
        self._document_id = None
        self._hashes = None
        self._link_existing_document = None
        self._object_key = None
        self._update_time = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if content_length is not None:
            self.content_length = content_length
        if content_type is not None:
            self.content_type = content_type
        if document_description is not None:
            self.document_description = document_description
        if document_id is not None:
            self.document_id = document_id
        if hashes is not None:
            self.hashes = hashes
        if link_existing_document is not None:
            self.link_existing_document = link_existing_document
        if object_key is not None:
            self.object_key = object_key
        if update_time is not None:
            self.update_time = update_time

    @property
    def address(self):
        """Gets the address of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The address of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ConquestApiChangeDocumentContentCommand.


        :param address: The address of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def content_length(self):
        """Gets the content_length of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The content_length of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: str
        """
        return self._content_length

    @content_length.setter
    def content_length(self, content_length):
        """Sets the content_length of this ConquestApiChangeDocumentContentCommand.


        :param content_length: The content_length of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: str
        """

        self._content_length = content_length

    @property
    def content_type(self):
        """Gets the content_type of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The content_type of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this ConquestApiChangeDocumentContentCommand.


        :param content_type: The content_type of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def document_description(self):
        """Gets the document_description of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The document_description of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: str
        """
        return self._document_description

    @document_description.setter
    def document_description(self, document_description):
        """Sets the document_description of this ConquestApiChangeDocumentContentCommand.


        :param document_description: The document_description of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: str
        """

        self._document_description = document_description

    @property
    def document_id(self):
        """Gets the document_id of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The document_id of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: int
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this ConquestApiChangeDocumentContentCommand.


        :param document_id: The document_id of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: int
        """

        self._document_id = document_id

    @property
    def hashes(self):
        """Gets the hashes of this ConquestApiChangeDocumentContentCommand.  # noqa: E501

        A list of calculated hashes / checksum of the file to be uploaded.  # noqa: E501

        :return: The hashes of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: list[str]
        """
        return self._hashes

    @hashes.setter
    def hashes(self, hashes):
        """Sets the hashes of this ConquestApiChangeDocumentContentCommand.

        A list of calculated hashes / checksum of the file to be uploaded.  # noqa: E501

        :param hashes: The hashes of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: list[str]
        """

        self._hashes = hashes

    @property
    def link_existing_document(self):
        """Gets the link_existing_document of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The link_existing_document of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: bool
        """
        return self._link_existing_document

    @link_existing_document.setter
    def link_existing_document(self, link_existing_document):
        """Sets the link_existing_document of this ConquestApiChangeDocumentContentCommand.


        :param link_existing_document: The link_existing_document of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: bool
        """

        self._link_existing_document = link_existing_document

    @property
    def object_key(self):
        """Gets the object_key of this ConquestApiChangeDocumentContentCommand.  # noqa: E501


        :return: The object_key of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: ConquestApiObjectKey
        """
        return self._object_key

    @object_key.setter
    def object_key(self, object_key):
        """Sets the object_key of this ConquestApiChangeDocumentContentCommand.


        :param object_key: The object_key of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: ConquestApiObjectKey
        """

        self._object_key = object_key

    @property
    def update_time(self):
        """Gets the update_time of this ConquestApiChangeDocumentContentCommand.  # noqa: E501

        UpdateTime when provided by the device can be used as a key, because a DocumentID is not yet present.  # noqa: E501

        :return: The update_time of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :rtype: datetime
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this ConquestApiChangeDocumentContentCommand.

        UpdateTime when provided by the device can be used as a key, because a DocumentID is not yet present.  # noqa: E501

        :param update_time: The update_time of this ConquestApiChangeDocumentContentCommand.  # noqa: E501
        :type: datetime
        """

        self._update_time = update_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiChangeDocumentContentCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiChangeDocumentContentCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
