# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiCopyAssetCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_id': 'int',
        'parent_id': 'int'
    }

    attribute_map = {
        'asset_id': 'AssetID',
        'parent_id': 'ParentID'
    }

    def __init__(self, asset_id=None, parent_id=None):  # noqa: E501
        """ConquestApiCopyAssetCommand - a model defined in Swagger"""  # noqa: E501
        self._asset_id = None
        self._parent_id = None
        self.discriminator = None
        if asset_id is not None:
            self.asset_id = asset_id
        if parent_id is not None:
            self.parent_id = parent_id

    @property
    def asset_id(self):
        """Gets the asset_id of this ConquestApiCopyAssetCommand.  # noqa: E501


        :return: The asset_id of this ConquestApiCopyAssetCommand.  # noqa: E501
        :rtype: int
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this ConquestApiCopyAssetCommand.


        :param asset_id: The asset_id of this ConquestApiCopyAssetCommand.  # noqa: E501
        :type: int
        """

        self._asset_id = asset_id

    @property
    def parent_id(self):
        """Gets the parent_id of this ConquestApiCopyAssetCommand.  # noqa: E501


        :return: The parent_id of this ConquestApiCopyAssetCommand.  # noqa: E501
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this ConquestApiCopyAssetCommand.


        :param parent_id: The parent_id of this ConquestApiCopyAssetCommand.  # noqa: E501
        :type: int
        """

        self._parent_id = parent_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiCopyAssetCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiCopyAssetCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
