# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiDisposalActionCompletionProcess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'measurement_after_disposal': 'ConquestApiDecimalValue'
    }

    attribute_map = {
        'measurement_after_disposal': 'MeasurementAfterDisposal'
    }

    def __init__(self, measurement_after_disposal=None):  # noqa: E501
        """ConquestApiDisposalActionCompletionProcess - a model defined in Swagger"""  # noqa: E501
        self._measurement_after_disposal = None
        self.discriminator = None
        if measurement_after_disposal is not None:
            self.measurement_after_disposal = measurement_after_disposal

    @property
    def measurement_after_disposal(self):
        """Gets the measurement_after_disposal of this ConquestApiDisposalActionCompletionProcess.  # noqa: E501


        :return: The measurement_after_disposal of this ConquestApiDisposalActionCompletionProcess.  # noqa: E501
        :rtype: ConquestApiDecimalValue
        """
        return self._measurement_after_disposal

    @measurement_after_disposal.setter
    def measurement_after_disposal(self, measurement_after_disposal):
        """Sets the measurement_after_disposal of this ConquestApiDisposalActionCompletionProcess.


        :param measurement_after_disposal: The measurement_after_disposal of this ConquestApiDisposalActionCompletionProcess.  # noqa: E501
        :type: ConquestApiDecimalValue
        """

        self._measurement_after_disposal = measurement_after_disposal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiDisposalActionCompletionProcess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiDisposalActionCompletionProcess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
