# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiCalculateDefectResponseDateParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'defect_id': 'int',
        'severity_id': 'int'
    }

    attribute_map = {
        'defect_id': 'DefectID',
        'severity_id': 'SeverityID'
    }

    def __init__(self, defect_id=None, severity_id=None):  # noqa: E501
        """ConquestApiCalculateDefectResponseDateParameters - a model defined in Swagger"""  # noqa: E501
        self._defect_id = None
        self._severity_id = None
        self.discriminator = None
        if defect_id is not None:
            self.defect_id = defect_id
        if severity_id is not None:
            self.severity_id = severity_id

    @property
    def defect_id(self):
        """Gets the defect_id of this ConquestApiCalculateDefectResponseDateParameters.  # noqa: E501


        :return: The defect_id of this ConquestApiCalculateDefectResponseDateParameters.  # noqa: E501
        :rtype: int
        """
        return self._defect_id

    @defect_id.setter
    def defect_id(self, defect_id):
        """Sets the defect_id of this ConquestApiCalculateDefectResponseDateParameters.


        :param defect_id: The defect_id of this ConquestApiCalculateDefectResponseDateParameters.  # noqa: E501
        :type: int
        """

        self._defect_id = defect_id

    @property
    def severity_id(self):
        """Gets the severity_id of this ConquestApiCalculateDefectResponseDateParameters.  # noqa: E501


        :return: The severity_id of this ConquestApiCalculateDefectResponseDateParameters.  # noqa: E501
        :rtype: int
        """
        return self._severity_id

    @severity_id.setter
    def severity_id(self, severity_id):
        """Sets the severity_id of this ConquestApiCalculateDefectResponseDateParameters.


        :param severity_id: The severity_id of this ConquestApiCalculateDefectResponseDateParameters.  # noqa: E501
        :type: int
        """

        self._severity_id = severity_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiCalculateDefectResponseDateParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiCalculateDefectResponseDateParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
