# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiGetCodeListsQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_id': 'list[int]',
        'code_list_id': 'list[int]',
        'code_list_name': 'list[str]'
    }

    attribute_map = {
        'code_id': 'CodeID',
        'code_list_id': 'CodeListID',
        'code_list_name': 'CodeListName'
    }

    def __init__(self, code_id=None, code_list_id=None, code_list_name=None):  # noqa: E501
        """ConquestApiGetCodeListsQuery - a model defined in Swagger"""  # noqa: E501
        self._code_id = None
        self._code_list_id = None
        self._code_list_name = None
        self.discriminator = None
        if code_id is not None:
            self.code_id = code_id
        if code_list_id is not None:
            self.code_list_id = code_list_id
        if code_list_name is not None:
            self.code_list_name = code_list_name

    @property
    def code_id(self):
        """Gets the code_id of this ConquestApiGetCodeListsQuery.  # noqa: E501

        if CodeID is greater than zero, the CodeList for this Code will be loaded.  # noqa: E501

        :return: The code_id of this ConquestApiGetCodeListsQuery.  # noqa: E501
        :rtype: list[int]
        """
        return self._code_id

    @code_id.setter
    def code_id(self, code_id):
        """Sets the code_id of this ConquestApiGetCodeListsQuery.

        if CodeID is greater than zero, the CodeList for this Code will be loaded.  # noqa: E501

        :param code_id: The code_id of this ConquestApiGetCodeListsQuery.  # noqa: E501
        :type: list[int]
        """

        self._code_id = code_id

    @property
    def code_list_id(self):
        """Gets the code_list_id of this ConquestApiGetCodeListsQuery.  # noqa: E501


        :return: The code_list_id of this ConquestApiGetCodeListsQuery.  # noqa: E501
        :rtype: list[int]
        """
        return self._code_list_id

    @code_list_id.setter
    def code_list_id(self, code_list_id):
        """Sets the code_list_id of this ConquestApiGetCodeListsQuery.


        :param code_list_id: The code_list_id of this ConquestApiGetCodeListsQuery.  # noqa: E501
        :type: list[int]
        """

        self._code_list_id = code_list_id

    @property
    def code_list_name(self):
        """Gets the code_list_name of this ConquestApiGetCodeListsQuery.  # noqa: E501


        :return: The code_list_name of this ConquestApiGetCodeListsQuery.  # noqa: E501
        :rtype: list[str]
        """
        return self._code_list_name

    @code_list_name.setter
    def code_list_name(self, code_list_name):
        """Sets the code_list_name of this ConquestApiGetCodeListsQuery.


        :param code_list_name: The code_list_name of this ConquestApiGetCodeListsQuery.  # noqa: E501
        :type: list[str]
        """

        self._code_list_name = code_list_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiGetCodeListsQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiGetCodeListsQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
