# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiMapObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group': 'int',
        'object_key': 'ConquestApiObjectKey',
        'object_name': 'str',
        'style': 'ConquestApiStyle',
        'wkt': 'str'
    }

    attribute_map = {
        'group': 'Group',
        'object_key': 'ObjectKey',
        'object_name': 'ObjectName',
        'style': 'Style',
        'wkt': 'Wkt'
    }

    def __init__(self, group=None, object_key=None, object_name=None, style=None, wkt=None):  # noqa: E501
        """ConquestApiMapObject - a model defined in Swagger"""  # noqa: E501
        self._group = None
        self._object_key = None
        self._object_name = None
        self._style = None
        self._wkt = None
        self.discriminator = None
        if group is not None:
            self.group = group
        if object_key is not None:
            self.object_key = object_key
        if object_name is not None:
            self.object_name = object_name
        if style is not None:
            self.style = style
        if wkt is not None:
            self.wkt = wkt

    @property
    def group(self):
        """Gets the group of this ConquestApiMapObject.  # noqa: E501


        :return: The group of this ConquestApiMapObject.  # noqa: E501
        :rtype: int
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this ConquestApiMapObject.


        :param group: The group of this ConquestApiMapObject.  # noqa: E501
        :type: int
        """

        self._group = group

    @property
    def object_key(self):
        """Gets the object_key of this ConquestApiMapObject.  # noqa: E501


        :return: The object_key of this ConquestApiMapObject.  # noqa: E501
        :rtype: ConquestApiObjectKey
        """
        return self._object_key

    @object_key.setter
    def object_key(self, object_key):
        """Sets the object_key of this ConquestApiMapObject.


        :param object_key: The object_key of this ConquestApiMapObject.  # noqa: E501
        :type: ConquestApiObjectKey
        """

        self._object_key = object_key

    @property
    def object_name(self):
        """Gets the object_name of this ConquestApiMapObject.  # noqa: E501


        :return: The object_name of this ConquestApiMapObject.  # noqa: E501
        :rtype: str
        """
        return self._object_name

    @object_name.setter
    def object_name(self, object_name):
        """Sets the object_name of this ConquestApiMapObject.


        :param object_name: The object_name of this ConquestApiMapObject.  # noqa: E501
        :type: str
        """

        self._object_name = object_name

    @property
    def style(self):
        """Gets the style of this ConquestApiMapObject.  # noqa: E501


        :return: The style of this ConquestApiMapObject.  # noqa: E501
        :rtype: ConquestApiStyle
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this ConquestApiMapObject.


        :param style: The style of this ConquestApiMapObject.  # noqa: E501
        :type: ConquestApiStyle
        """

        self._style = style

    @property
    def wkt(self):
        """Gets the wkt of this ConquestApiMapObject.  # noqa: E501


        :return: The wkt of this ConquestApiMapObject.  # noqa: E501
        :rtype: str
        """
        return self._wkt

    @wkt.setter
    def wkt(self, wkt):
        """Sets the wkt of this ConquestApiMapObject.


        :param wkt: The wkt of this ConquestApiMapObject.  # noqa: E501
        :type: str
        """

        self._wkt = wkt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiMapObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiMapObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
