# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiIssueWorkOrderCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_id': 'int',
        'contractor_email_metadata': 'ConquestApiContractorEmailMetadata',
        'issue_by': 'ConquestApiIssueBy',
        'issue_date': 'datetime',
        'related_documents': 'list[ConquestApiDocument]',
        'report': 'ConquestApiReport'
    }

    attribute_map = {
        'action_id': 'ActionID',
        'contractor_email_metadata': 'ContractorEmailMetadata',
        'issue_by': 'IssueBy',
        'issue_date': 'IssueDate',
        'related_documents': 'RelatedDocuments',
        'report': 'Report'
    }

    def __init__(self, action_id=None, contractor_email_metadata=None, issue_by=None, issue_date=None, related_documents=None, report=None):  # noqa: E501
        """ConquestApiIssueWorkOrderCommand - a model defined in Swagger"""  # noqa: E501
        self._action_id = None
        self._contractor_email_metadata = None
        self._issue_by = None
        self._issue_date = None
        self._related_documents = None
        self._report = None
        self.discriminator = None
        if action_id is not None:
            self.action_id = action_id
        if contractor_email_metadata is not None:
            self.contractor_email_metadata = contractor_email_metadata
        if issue_by is not None:
            self.issue_by = issue_by
        if issue_date is not None:
            self.issue_date = issue_date
        if related_documents is not None:
            self.related_documents = related_documents
        if report is not None:
            self.report = report

    @property
    def action_id(self):
        """Gets the action_id of this ConquestApiIssueWorkOrderCommand.  # noqa: E501


        :return: The action_id of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :rtype: int
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id):
        """Sets the action_id of this ConquestApiIssueWorkOrderCommand.


        :param action_id: The action_id of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :type: int
        """

        self._action_id = action_id

    @property
    def contractor_email_metadata(self):
        """Gets the contractor_email_metadata of this ConquestApiIssueWorkOrderCommand.  # noqa: E501


        :return: The contractor_email_metadata of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :rtype: ConquestApiContractorEmailMetadata
        """
        return self._contractor_email_metadata

    @contractor_email_metadata.setter
    def contractor_email_metadata(self, contractor_email_metadata):
        """Sets the contractor_email_metadata of this ConquestApiIssueWorkOrderCommand.


        :param contractor_email_metadata: The contractor_email_metadata of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :type: ConquestApiContractorEmailMetadata
        """

        self._contractor_email_metadata = contractor_email_metadata

    @property
    def issue_by(self):
        """Gets the issue_by of this ConquestApiIssueWorkOrderCommand.  # noqa: E501


        :return: The issue_by of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :rtype: ConquestApiIssueBy
        """
        return self._issue_by

    @issue_by.setter
    def issue_by(self, issue_by):
        """Sets the issue_by of this ConquestApiIssueWorkOrderCommand.


        :param issue_by: The issue_by of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :type: ConquestApiIssueBy
        """

        self._issue_by = issue_by

    @property
    def issue_date(self):
        """Gets the issue_date of this ConquestApiIssueWorkOrderCommand.  # noqa: E501


        :return: The issue_date of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :rtype: datetime
        """
        return self._issue_date

    @issue_date.setter
    def issue_date(self, issue_date):
        """Sets the issue_date of this ConquestApiIssueWorkOrderCommand.


        :param issue_date: The issue_date of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :type: datetime
        """

        self._issue_date = issue_date

    @property
    def related_documents(self):
        """Gets the related_documents of this ConquestApiIssueWorkOrderCommand.  # noqa: E501


        :return: The related_documents of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :rtype: list[ConquestApiDocument]
        """
        return self._related_documents

    @related_documents.setter
    def related_documents(self, related_documents):
        """Sets the related_documents of this ConquestApiIssueWorkOrderCommand.


        :param related_documents: The related_documents of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :type: list[ConquestApiDocument]
        """

        self._related_documents = related_documents

    @property
    def report(self):
        """Gets the report of this ConquestApiIssueWorkOrderCommand.  # noqa: E501


        :return: The report of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :rtype: ConquestApiReport
        """
        return self._report

    @report.setter
    def report(self, report):
        """Sets the report of this ConquestApiIssueWorkOrderCommand.


        :param report: The report of this ConquestApiIssueWorkOrderCommand.  # noqa: E501
        :type: ConquestApiReport
        """

        self._report = report

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiIssueWorkOrderCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiIssueWorkOrderCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
