# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiCriteriaItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_list': 'ConquestApiFieldCriterionList',
        'fields': 'ConquestApiFieldCriterionList',
        'group': 'ConquestApiCriteria'
    }

    attribute_map = {
        'field_list': 'FieldList',
        'fields': 'Fields',
        'group': 'Group'
    }

    def __init__(self, field_list=None, fields=None, group=None):  # noqa: E501
        """ConquestApiCriteriaItem - a model defined in Swagger"""  # noqa: E501
        self._field_list = None
        self._fields = None
        self._group = None
        self.discriminator = None
        if field_list is not None:
            self.field_list = field_list
        if fields is not None:
            self.fields = fields
        if group is not None:
            self.group = group

    @property
    def field_list(self):
        """Gets the field_list of this ConquestApiCriteriaItem.  # noqa: E501


        :return: The field_list of this ConquestApiCriteriaItem.  # noqa: E501
        :rtype: ConquestApiFieldCriterionList
        """
        return self._field_list

    @field_list.setter
    def field_list(self, field_list):
        """Sets the field_list of this ConquestApiCriteriaItem.


        :param field_list: The field_list of this ConquestApiCriteriaItem.  # noqa: E501
        :type: ConquestApiFieldCriterionList
        """

        self._field_list = field_list

    @property
    def fields(self):
        """Gets the fields of this ConquestApiCriteriaItem.  # noqa: E501


        :return: The fields of this ConquestApiCriteriaItem.  # noqa: E501
        :rtype: ConquestApiFieldCriterionList
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this ConquestApiCriteriaItem.


        :param fields: The fields of this ConquestApiCriteriaItem.  # noqa: E501
        :type: ConquestApiFieldCriterionList
        """

        self._fields = fields

    @property
    def group(self):
        """Gets the group of this ConquestApiCriteriaItem.  # noqa: E501


        :return: The group of this ConquestApiCriteriaItem.  # noqa: E501
        :rtype: ConquestApiCriteria
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this ConquestApiCriteriaItem.


        :param group: The group of this ConquestApiCriteriaItem.  # noqa: E501
        :type: ConquestApiCriteria
        """

        self._group = group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiCriteriaItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiCriteriaItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
