# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiAddNewCsvImportCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filename': 'str',
        'import_type': 'str',
        'user_filename': 'str'
    }

    attribute_map = {
        'filename': 'filename',
        'import_type': 'import_type',
        'user_filename': 'user_filename'
    }

    def __init__(self, filename=None, import_type=None, user_filename=None):  # noqa: E501
        """ConquestApiAddNewCsvImportCommand - a model defined in Swagger"""  # noqa: E501
        self._filename = None
        self._import_type = None
        self._user_filename = None
        self.discriminator = None
        if filename is not None:
            self.filename = filename
        if import_type is not None:
            self.import_type = import_type
        if user_filename is not None:
            self.user_filename = user_filename

    @property
    def filename(self):
        """Gets the filename of this ConquestApiAddNewCsvImportCommand.  # noqa: E501


        :return: The filename of this ConquestApiAddNewCsvImportCommand.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this ConquestApiAddNewCsvImportCommand.


        :param filename: The filename of this ConquestApiAddNewCsvImportCommand.  # noqa: E501
        :type: str
        """

        self._filename = filename

    @property
    def import_type(self):
        """Gets the import_type of this ConquestApiAddNewCsvImportCommand.  # noqa: E501


        :return: The import_type of this ConquestApiAddNewCsvImportCommand.  # noqa: E501
        :rtype: str
        """
        return self._import_type

    @import_type.setter
    def import_type(self, import_type):
        """Sets the import_type of this ConquestApiAddNewCsvImportCommand.


        :param import_type: The import_type of this ConquestApiAddNewCsvImportCommand.  # noqa: E501
        :type: str
        """

        self._import_type = import_type

    @property
    def user_filename(self):
        """Gets the user_filename of this ConquestApiAddNewCsvImportCommand.  # noqa: E501


        :return: The user_filename of this ConquestApiAddNewCsvImportCommand.  # noqa: E501
        :rtype: str
        """
        return self._user_filename

    @user_filename.setter
    def user_filename(self, user_filename):
        """Sets the user_filename of this ConquestApiAddNewCsvImportCommand.


        :param user_filename: The user_filename of this ConquestApiAddNewCsvImportCommand.  # noqa: E501
        :type: str
        """

        self._user_filename = user_filename

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiAddNewCsvImportCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiAddNewCsvImportCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
