# coding: utf-8

"""
    Conquest API v4

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConquestApiMapObjectsRecordSet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'objects': 'list[ConquestApiMapObject]',
        'context_descriptor': 'ConquestApiContextDescriptor',
        'context_descriptors_for_groups': 'list[ConquestApiContextDescriptor]'
    }

    attribute_map = {
        'objects': 'Objects',
        'context_descriptor': 'contextDescriptor',
        'context_descriptors_for_groups': 'contextDescriptorsForGroups'
    }

    def __init__(self, objects=None, context_descriptor=None, context_descriptors_for_groups=None):  # noqa: E501
        """ConquestApiMapObjectsRecordSet - a model defined in Swagger"""  # noqa: E501
        self._objects = None
        self._context_descriptor = None
        self._context_descriptors_for_groups = None
        self.discriminator = None
        if objects is not None:
            self.objects = objects
        if context_descriptor is not None:
            self.context_descriptor = context_descriptor
        if context_descriptors_for_groups is not None:
            self.context_descriptors_for_groups = context_descriptors_for_groups

    @property
    def objects(self):
        """Gets the objects of this ConquestApiMapObjectsRecordSet.  # noqa: E501


        :return: The objects of this ConquestApiMapObjectsRecordSet.  # noqa: E501
        :rtype: list[ConquestApiMapObject]
        """
        return self._objects

    @objects.setter
    def objects(self, objects):
        """Sets the objects of this ConquestApiMapObjectsRecordSet.


        :param objects: The objects of this ConquestApiMapObjectsRecordSet.  # noqa: E501
        :type: list[ConquestApiMapObject]
        """

        self._objects = objects

    @property
    def context_descriptor(self):
        """Gets the context_descriptor of this ConquestApiMapObjectsRecordSet.  # noqa: E501


        :return: The context_descriptor of this ConquestApiMapObjectsRecordSet.  # noqa: E501
        :rtype: ConquestApiContextDescriptor
        """
        return self._context_descriptor

    @context_descriptor.setter
    def context_descriptor(self, context_descriptor):
        """Sets the context_descriptor of this ConquestApiMapObjectsRecordSet.


        :param context_descriptor: The context_descriptor of this ConquestApiMapObjectsRecordSet.  # noqa: E501
        :type: ConquestApiContextDescriptor
        """

        self._context_descriptor = context_descriptor

    @property
    def context_descriptors_for_groups(self):
        """Gets the context_descriptors_for_groups of this ConquestApiMapObjectsRecordSet.  # noqa: E501


        :return: The context_descriptors_for_groups of this ConquestApiMapObjectsRecordSet.  # noqa: E501
        :rtype: list[ConquestApiContextDescriptor]
        """
        return self._context_descriptors_for_groups

    @context_descriptors_for_groups.setter
    def context_descriptors_for_groups(self, context_descriptors_for_groups):
        """Sets the context_descriptors_for_groups of this ConquestApiMapObjectsRecordSet.


        :param context_descriptors_for_groups: The context_descriptors_for_groups of this ConquestApiMapObjectsRecordSet.  # noqa: E501
        :type: list[ConquestApiContextDescriptor]
        """

        self._context_descriptors_for_groups = context_descriptors_for_groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConquestApiMapObjectsRecordSet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConquestApiMapObjectsRecordSet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
