# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConquestGeoDialog
                                 A QGIS plugin
 This plugin connects to your Conquest assets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-10
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Conquest Software Pty Ltd.
        email                : support@conquestsoftware.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt.QtCore import QSettings
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from  ui.client import client

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'conquest_geo_dialog_base.ui'))


class ConquestGeoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ConquestGeoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.accepted.connect(self._submit_form)
        self.url_input.setText(client.url)
        self.token_input.setText(client.token)

    def _print_api(self):
        print(str(self.url_input.text()))

    def _submit_form(self):
        self._print_api()
        client.url = self.url_input.text()
        client.token = self.token_input.text()
